#!/usr/bin/env python3
"""Curate a *readable* failure-mode digest from the 1,033-Q MEVA CrossView run.

The bulk `*_failures.md` files dump every failure verbatim (~12 MB). This instead
tags each Qwen failure with a coarse mechanism, reports how prevalent each is per
task type / camera count, and quotes a few representative traces per bucket.

Mechanisms tagged (Qwen, which carries <think> traces + full metadata):
  - truncation_no_answer : ran past the 8192-token budget / abstained (no <answer>)
  - given_order_bias     : (Event-Ordering) predicted the as-listed I->II->III order
  - single_video_shortcut: reasoned over one clip on a >=2-video question
  - wrong_reasoned       : emitted a real answer, just wrong

Usage:
  python analysis/curate_failure_examples.py \
      --qwen Video-R1/src/r1-v/eval_results/eval_crossview_meva1033_qwen3vl.json \
      --internvl analysis/crossview_internvl3_meva1033_normalized.json \
      --out analysis/crossview_meva1033_out/failure_examples_curated.md
"""
import argparse, json, re
from collections import Counter, defaultdict

ROMAN = ["I", "II", "III", "IV", "V", "VI"]


def load(path):
    d = json.load(open(path))
    return d["results"] if isinstance(d, dict) and "results" in d else d


def acc_table(recs, key):
    by = defaultdict(lambda: [0, 0])
    for r in recs:
        k = r.get(key)
        if k is None:
            continue
        by[k][1] += 1
        by[k][0] += 1 if r.get("correct") else 0
    return by


def ascending_option(options):
    """Index of the option that lists events in as-given ascending order (I->II->III...)."""
    for opt in options:
        seq = re.findall(r"\b(I{1,3}|IV|V?I{0,3})\b", opt.split(".", 1)[-1])
        seq = [s for s in seq if s]
        if seq and seq == ROMAN[: len(seq)]:
            return opt.strip()[0]  # the letter
    return None


def pred_letter(r):
    p = str(r.get("prediction") or "").strip()
    return p[:1].upper() if p else ""


def has_answer(r):
    return "<answer>" in (r.get("output") or "") and bool(str(r.get("prediction") or "").strip())


def think_excerpt(r, n=600):
    t = (r.get("think") or "").strip()
    if not t:
        out = (r.get("output") or "").strip()
        t = re.sub(r"<answer>.*?</answer>", "", out, flags=re.S).strip()
    t = re.sub(r"\s+", " ", t)
    return t[:n] + (" …[trimmed]" if len(t) > n else "")


def single_video_shortcut(r):
    if (r.get("num_videos") or 0) < 2:
        return False
    t = (r.get("think") or r.get("output") or "").lower()
    mentions = {v for v in ("video 2", "video 3", "video 4") if v in t}
    return ("the video" in t or "video 1" in t) and not mentions


def tag(r):
    if not has_answer(r):
        return "truncation_no_answer"
    if r["task_type"].endswith("Event-Ordering"):
        asc = ascending_option(r.get("options", []))
        if asc and pred_letter(r) == asc:
            return "given_order_bias"
    if single_video_shortcut(r):
        return "single_video_shortcut"
    return "wrong_reasoned"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--qwen", required=True)
    ap.add_argument("--internvl", default=None)
    ap.add_argument("--out", required=True)
    ap.add_argument("--per-bucket", type=int, default=2)
    a = ap.parse_args()

    q = load(a.qwen)
    iv = {str(r["id"]): r for r in load(a.internvl)} if a.internvl else {}
    # attach task_type to InternVL via the Qwen id->task_type map
    tt = {str(r["id"]): r["task_type"] for r in q}
    for k, r in iv.items():
        r["task_type"] = tt.get(k)

    wrong = [r for r in q if not r.get("correct")]
    for r in wrong:
        r["_mech"] = tag(r)

    L = []
    correct = sum(r["correct"] for r in q)
    L.append("# CrossView MEVA 1,033-Q — curated failure-mode digest (Qwen3-VL-8B-Thinking)\n")
    L.append(f"Overall (eval-time parser): {correct}/{len(q)} = {100*correct/len(q):.1f}%. "
             f"Wrong: {len(wrong)}. Generated by `analysis/curate_failure_examples.py` "
             "(reproducible). Full verbatim dumps remain in `qwen3vl_failures.md`.\n")
    L.append("> **Parser note:** `analyze_failures.py` re-parses the raw outputs and recovers "
             "~12 borderline answers the eval-time parser scored wrong, so the camera-curve "
             "reports cite **32.0% (331/1033)** vs the **30.9% (319/1033)** stored in the eval "
             "JSON's `correct` field. The ~1pp gap is those 12 parse-recoverable cases; the "
             "failure-mechanism proportions below are parser-insensitive.\n")

    # accuracy comparison tables
    L.append("## Accuracy by task type\n")
    L.append("| task | Qwen | InternVL3 |\n|---|---:|---:|")
    qbt, ibt = acc_table(q, "task_type"), acc_table(list(iv.values()), "task_type")
    for t in sorted(qbt):
        qc, qn = qbt[t]
        ic, ino = ibt.get(t, [0, 0])
        iv_s = f"{100*ic/ino:.0f}% ({ic}/{ino})" if ino else "—"
        L.append(f"| {t.replace('CrossView-MEVA-','')} | {100*qc/qn:.0f}% ({qc}/{qn}) | {iv_s} |")

    L.append("\n## Accuracy by original #cameras (Qwen)\n")
    L.append("| #cameras | acc | n |\n|---:|---:|---:|")
    for c, (cc, cn) in sorted(acc_table(q, "orig_num_cameras").items()):
        L.append(f"| {c} | {100*cc/cn:.0f}% | {cn} |")

    # mechanism prevalence
    L.append("\n## Failure mechanism prevalence (Qwen, of all wrong)\n")
    L.append("| mechanism | count | by task |\n|---|---:|---|")
    mech_by_task = defaultdict(Counter)
    for r in wrong:
        mech_by_task[r["_mech"]][r["task_type"].replace("CrossView-MEVA-", "")] += 1
    for m, total in Counter(r["_mech"] for r in wrong).most_common():
        bt = ", ".join(f"{k} {v}" for k, v in mech_by_task[m].most_common())
        L.append(f"| {m} | {total} | {bt} |")

    # representative examples per (task, mechanism)
    L.append("\n## Representative examples\n")
    buckets = defaultdict(list)
    for r in wrong:
        buckets[(r["task_type"], r["_mech"])].append(r)
    for (t, m), rs in sorted(buckets.items()):
        L.append(f"\n### {t.replace('CrossView-MEVA-','')} — {m}  ({len(rs)} cases)\n")
        for r in rs[: a.per_bucket]:
            ivr = iv.get(str(r["id"]))
            iv_note = ""
            if ivr is not None:
                iv_note = f" · InternVL3 {'✓' if ivr.get('correct') else '✗'} ({ivr.get('prediction') or '—'})"
            L.append(f"- **id {r['id']}** · {r.get('num_videos')} vids · "
                     f"orig {r.get('orig_num_cameras')} cams · gold **{r.get('answer')}** · "
                     f"pred **{r.get('prediction') or '∅'}**{iv_note}")
            L.append(f"  - Q: {re.sub(chr(92)+'s+',' ', r['question'])[:240]}")
            L.append(f"  - trace: > {think_excerpt(r)}")

    body = "\n".join(L)
    open(a.out, "w").write(body + "\n")
    print(f"wrote {a.out} ({len(body)} bytes); {len(wrong)} failures, "
          f"{len(buckets)} (task x mechanism) buckets")


if __name__ == "__main__":
    main()
